server:
  servlet.contextPath: /
  port: 8103

spring:
  application:
    name: archive-service-api
  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    database: POSTGRESQL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5439/archive
    password: pass
    username: user

archive:
  zip:
    max-upload-size: 1048576