services:

  posgress_sql_service_archive:
    image: 'postgres'
    container_name: posgress_sql_service_archive
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=archive
    ports:
      - 5439:5432
    networks:
      - default